### ISSUE TITLE
multi-select breaks the combo box

### ISSUE THREAD

**Issue by optikalefx** [AnnotationSro/ember-advanced-combobox#4]
I was looking for a combo box with multi-select. I tried yours out here https://ember-twiddle.com/d7e525fdf8cdc186d40d0e705377bf8c but when multi-select is true, it fails.

**Comment by IgorKvasn** [comment]
Hi,
thanks for the bug report - there is definitely something wrong there, I will take a look at it.

**Comment by IgorKvasn** [comment]
Hi,
I released new version of the addon that fixes some problems with multiselect support, however there is one more thing to mention - consuming app must have FontAwesome included.
It seems I forgot to mention it in readme as well, so I added:

> This addon uses FontAwesome by default - at the moment you have to provide it for yourself (this addon does not install it for you). You can however use any font icon set you want, but do not forget to configure this addon (more in section Global configuration -> propery icons)


See my twiddle for more details:
https://ember-twiddle.com/8afad1baa36cc608c78c9da5268c6084

**Comment by optikalefx** [comment]
Thanks for pushing that update. This addon is the preferred way to do multi-select (using checkboxes). I will probably make a PR to remove FontAwesome support. While we actually do have FA in my project, I can't think of a good reasons to 1) not use a normal checkbox and 2) have a dependency on this project that isn't included.

**Comment by IgorKvasn** [comment]
FA icons are used also to indicate asynchronous loading of dropdown content, otherwise I guess FA can be removed and replaced with simple unicode characters...

but feel free to make a PR with your ideas :+1:
